index.js
I'm trying to use gulp-webpack with wallaby, and I found that in some cases, entry = 'string', which doesn't have .push so it fails on line 73.
=> reset entry to [] after we don't need it

readme.md
Updated the README to note that the use of `watch` will decrease compilation times rather than increase
=> [Documentation] Watch will help *decrease* compilation times

index.js
If you dynamically create a task like so:
```js
function build(module) {
return gulp.src('src/' + module)
.pipe(webpack(webpackConfig))
.pipe(gulp.dest('public/' + module));
}
gulp.task('build-a', function() { return build('a.js'); });
gulp.task('build-b', function() { return build('b.js'); });
gulp.task('default', ['build-a', 'build-b']);
```
When running `gulp default`, [options.entry](https://github.com/shama/webpack-stream/blob/master/index.js#L91) would be `src/a.js` both times.
To avoid that, we make a shallow copy of `options` and modify that instead.
=> Avoid modifying options by reference

index.js, package.json, test/test.js
Fixes #40
I was quite surprised that a project as mature as Webpack didn't have the tooling to support source maps with Gulp. :unamused: Source maps are essential!
=> Add support for source maps

index.js
This was the [pre 2.2.0](https://github.com/shama/webpack-stream/commit/08c045339561ab8f020953c9374f8544f6c8d21e#diff-168726dbe96b3ce427e7fedce31bb0bcL146) behaviour. I tested it locally and confirmed it fixes the broken fonts :smile: 
Closes #87
=> Fix fonts passed through the stream

index.js
No `error` event should be emitted on a compilation error when watching, because node stops writing data after an `error` event. See https://github.com/shama/webpack-stream/issues/34#issuecomment-244534449 for a detailed description.
Instead, we can always safely emit a `compilation-error` event. This makes sure that others are still able listen for compilation errors. Additionally, when we are not in watch mode, we do emit an `error` event to keep the behavior the same and do not break backwards compatibility for non-watching tasks.
=> No error event on compilation error when watching

readme.md
Updated README.md to include an example for how to run with a multi-compiler configuration.
As mentioned in #124 .
=> Added example for multi-compiler support

index.js
Before fixing this issue user gets message: "TypeError: Cannot read property 'toJson' of undefined" and a stack trace.
After adding proposed check user is getting regular gulp error message with sense.
=> Fix TypeError when 'stats' are undefined

index.js
Memory-fs.join has a different behavior comparing to node's path.join when the non-first argument contains / or . And it'll cause a bug when filename contains / or (only webpack is all right).
so, at least, we should use node's path.join when w'll interact with real fs.
renaesop/wepack-stream-issue#1
=> Fix a bug: output.filename starts with / will raise error

.travis.yml
Builds are currently [failing](https://travis-ci.org/shama/webpack-stream/builds/261894688) because of `0.10`.
Getting rid of `0.10` seems to be appropriate since it’s end-of-life since since 2016-10-31.
https://github.com/nodejs/Release#release-schedule
=> Update Travis config: Remove node 0.10 and add latest node version

index.js, package.json
At some point, chalk.supportsColor changed so that it returns an object rather than a boolean or webpack changed so that it requires a boolean. This results in a `WebpackOptionsValidationError` error thrown after the first run of webpack-stream as it mutates the configuration option with it's defaults.
When trying to figure out if/what version of chalk made this change to check for backwards compatibility issues, I realised we don't use any other aspects of chalk, and given chalk uses supports-color to power supportsColor anyway it seemed to make sense to just use that dependancy directly.
This PR changes to support-color, and fixes the issue where an invalid object is passed into webpack's configuration if your own webpack.config.js doesn't contain stats.colors.
=> Switch to supports-color over chalk

index.js
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
This change fixes the deprecation warning but ensure supports with both Webpack 2/3 & 4.
=> Fix Webpack 4 deprecation warning

index.js, test/fake-error-loader.js, test/test.js
When emitting "error" and "compilation-error" events on the stream, underlying errors reported as `stats.errors` by Webpack were joined without newlines.  This could lead to error messages like these (taken from the build output of a project that uses `webpack-stream` and `ts-loader`):
```
[tsl] ERROR in D:\frontend\app\views\SampleView.ts(8,2)
TS2564: Property '_parentEntity' has no initializer and is not definitely assigned in the constructor../app/views/SampleView.ts
[tsl] ERROR in D:\frontend\...
```
Note the absence of a newline before `../app/views/SampleView.ts`.
In this commit:
1. Individual error messages are joined with `\n`.
2. A `test('error formatting')` is added that checks error formatting using a fake Webpack loader producing some errors (`test/fake-error-loader.js`).
=> Separate errors with newlines.

.travis.yml, package.json, test/test.js
- Updates Webpack to version 4 and fixes the unit tests.
- Sets the engine to minimal version of 6.11.5, the same on Webpack 4.
- Remove Node 4 from TravisCI settings
This PR keep Webpack as a project dependency since the webpack documentation says if you use this module you don't need to install webpack as a project dependency:
https://webpack.js.org/guides/integrations/#gulp
=> Adds webpack 4 support

index.js
webpack support stats options as  string, but only allow object here .
fix issuse: #185
reference: https://webpack.js.org/configuration/stats/
=> fix missing type checking for statsOptions. 

index.js
[`Array.prototype.some`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) is implemented in all recent versions of node.js, so you can remove the dependency to `lodash.some`.
*I did not actually remove the dependency from `package.json`, just in case it's used elsewhere and I missed it. If you merge this PR, remember that the dependency should be removed.*
=> Remove dependency to lodash.some

index.js
Fixing issue 201 by preventing cache.compiler from ever being the same instance for separately created instances of webpack-stream. This issue prevents webpack-stream from compiling the same file for multiple targets.
=> Fix issue 201 by moving cache to the function.

index.js
Error messages from jsonStats errors was constructed by `errors.join('\n')` which resulted in a message like `[object Object]`.
This fix tries to resolve the actual error message from error objects via some naive heuristics
=> Extract error messages from jsonStats errors

index.js, package.json
Fixes GH-230
Alternative to GH-231
@cowwoc how about this solution? That way those who still want to use the webpack `watch` option can. 
If you're calling `webpack.watch()` (which this lib does with `watch: true`), then you don't need to additionally supply `watch: true` to the webpack config: https://github.com/webpack/webpack-cli/issues/1918#issuecomment-714419766
=> Fix for webpack 5 watch mode deprecation: DEP_WEBPACK_WATCH_WITHOUT_CALLBACK

index.js, test/fixtures/webpack.config.js, test/test.js
This is useful for when using a typescript `gulpfile.ts` and when a dynamic import has to be truly dynamic. Since this is not possible within typescript. For instance you could do something like this:
```typescript
...
["a", "b", "c"].map(x => async () => 
src("src/*.ts")
.pipe(
webpack({
config: path.resolve(path.join(__dirname, x))
})
// or
webpack(path.resolve(path.join(__dirname, x)))
)
);
...
```
Obviously the example above is not that dynamic, but it gives you an idea of what could be. 
Anyway, with that said, the commit is probably not of best quality. There's definitely more. However, gives me something to work with. Discuss what you'd like to see more, and I can see what I can do. I thought of it as a start for now.
=> Added support for loading webpack config from file path.

index.js
This change prints `webpack compilation starting...` after a new compilation is triggered during watch mode.
This helps user know their file change has been detected and something is happening.
=> Display message on watch compilation start

index.js
hard coding a default of `'[hash].js'` for `config.output.filename` means that multiple outputs don't work.
=> fixed single output only bug
